[project]
name = "integration-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pytest-lsp>=0.4.3", "pytest>=8.3.4", "lsprotocol>=2023.0.1"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
