id = "codebook"
name = "Codebook"
version = "0.1.0"
description = "Zed extension for codebook."
authors = ["Bo"]
license = "MIT"
schema_version = 1
# repository = "https://github.com/your-name/my-zed-extension"

[language_servers.codebook]
name = "codebook"
languages = [
    "Markdown",
    "Plain Text",
    "HTML",
    "CSS",
    "Go",
    "JavaScript",
    "JavaScript React",
    "Python",
    "Rust",
    "TypeScript",
    "TypeScript React",
]
