[package]
name = "codebook-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
anyhow = "1.0"
glob = "0.3"


[dev-dependencies]
tempfile = "3"
