name: Release
on:
  workflow_run:
    workflows: ["Test", "Binaries"]
    branches: [main]
    tags:
      - v*
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts
          pattern: codebook-lsp-*
          run-id: ${{ github.event.workflow_run.id }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/codebook-lsp*
          prerelease: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          draft: false
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
